### ISSUE TITLE
Table of contents block - handling duplicate IDs

### ISSUE THREAD

**Issue by LukaszJaro** [brainstormforce/ultimate-addons-for-gutenberg#136]
Hi,

Right now I see a serial number is appended to the ID, is it feasible to only append a number if there is conflicting duplicate ID? Just like WordPress handles the post slug using wp_unique_post_slug?

Also like WP, append the number at the end like so: "heading-2"

**Comment by vrundakansara** [comment]
Hey @LukaszJaro ,

These are the Anchor Ids, which are expected to be added by the user since they will be visible in the URL bar in the browser.

But we didn't want to increase user's efforts so we autogenerate them. You can always edit them as per your needs. They will be reflected accordingly in the Table of Contents block.

Regards,
Vrunda Kansara
