### ISSUE TITLE
Post Carousel shows most recent posts in all languages

### ISSUE THREAD

**Issue by mikeweltevrede** [brainstormforce/ultimate-addons-for-gutenberg#159]
I am using Polylang to maintain a website that is available in Dutch and English. However, if I use the Post Carousel, it shows me the articles in both Dutch and English while I only want to see the posts of the corresponding website (a static Homepage assigned to this language). I have currently found a workaround where I simply create a Category for the language and edit the Post Carousel settings accordingly but this should seem superfluous.

**Comment by vrundakansara** [comment]
Hey @mikeweltevrede ,
Ultimate Addon for Gutenberg works without any issues with the Polylang plugin.

Both languages' posts are visible to you in the backend for Post Carousel.
But when you actually publish the page and see the Post Carousel in the front end, you will see the respective language posts only.

This is because Polylang hooks into the WP Query only in the frontend.
If still, you face any issues please reach us out from [here.](https://www.ultimategutenberg.com/support/)

Regards,
Vrunda Kansara
