### ISSUE TITLE
Taxonomy List links broken for custom taxonomies if term contains spaces

### ISSUE THREAD

**Issue by matjemeisje** [brainstormforce/ultimate-addons-for-gutenberg#422]
When adding a taxonomy list block for a custom taxonomy and custom post type, I get the following warning on all terms that contain spaces: "ltrim() expects parameter 1 to be string, object given".

The terms display okay in the editor, but on the frontend only the post count is displayed, and the url is replaced with the warning message.

**Comment by amithire1201** [comment]
Hey @matjemeisje 

Apologize for inconvenience.

We have fixed this issue and it will surely be released in our upcoming update.

If you want a development version of this fix then, Please open a [ticket](https://www.ultimategutenberg.com/support/open-a-ticket/) here, So that we can provide you with the same.

Looking forward to hearing from you.

Regards,
Amit

**Comment by matjemeisje** [comment]
Hi @amithire1201 

Thank you for the quick response! I'll wait for the update.
