### ISSUE TITLE
Gravity Form Styler won't show form

### ISSUE THREAD

**Issue by KristofferBroberg** [brainstormforce/ultimate-addons-for-gutenberg#697]
### Describe the bug:
When choosing form to style in the Gravity Form Style block, the block instantly disappears.

### To reproduce:
1. Insert Gravity Form Styler block
2. Choose your form

### Expected behavior:
See form and be able to customize its appearance.

### Isolating the problem:

- [ X] I can reproduce this bug consistently using the steps above

### WordPress version:
5.7.2

### Gravity form version
2.5

### UAG version
1.22.5

### Astra version
3.4.4

### Astra Pro version
3.4.2

**Comment by AbhijitNage123** [comment]
Hello @KristofferBroberg,

Thanks for reaching out to us.

It seems that you're using Gravity form conditional logic. Due to that, it has an inline style of display: none applied as mention by [GF Forms](https://share.getcloudapp.com/12uAGbNN). So the solution to your query needs to use some custom CSS in the backend.

Could you please add the below code in your themes function.php -

```
add_action( 'admin_footer', 'custom_internal_css' );
 
function custom_internal_css(){
 
	echo '<style>
		.wp-block-uagb-gf-styler .gform_wrapper{
				display:block !important;
			}
		</style>';
 
}
```

I hope this helps you to resolve your query.

**Comment by KristofferBroberg** [comment]
Hello @AbhijitNage123 and thanks for your help. Unfortunately, this solution comes with other problems:

1. The same CSS-rule has to be applied to the front end
2.  It breaks the conditional functions of the form. I. E fields that shouldn't show does.

**Comment by AbhijitNage123** [comment]
Hello @KristofferBroberg,

Sorry for the delay in response.

The CSS I shared in the previous response is only applied to the admin_footer in the editor area. It does not load on the front end.

Could you please share what exactly breaking with GF-Styler block? Could you please share some screencasts?

Please share more details [here](https://ultimategutenberg.com/support/open-a-ticket/) on our support portal.

Looking forward to resolving your issue.
